Repository Chit-Chat-Org/Chit-Chat, pull requests merged in 2024-05, with the labels that each got.

#11 #8-update-CODE-OF-CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, gssoc

#27 added workflow for closing old issues
  .github/workflows/close-old-issue.yml
Labels: documentation, gssoc, level1

#26 added workflow for closing old PRs
  .github/workflows/close-old-pr.yml
Labels: documentation, enhancement, level1
